services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: software
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - '5555:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
